name: Development and Staging Deployment Workflow

on:
  push:
    branches:
      - development
  
jobs:
  Job_1:
    name: Install and testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.14.0]

    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install
      run: npm install package.json
  
  Job_2:
    name: Create tag, Build, and Deployment
    needs: Job_1
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Create Tag
      uses: anothrNick/github-tag-action@master
      id: get_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: 'patch'
        WITH_V: false
        RELEASE_BRANCHES: .*

    - name: Get Version
      run: echo ${{steps.get_tag.outputs.new_tag}}

    # - name: Docker Build Dev with Tag
    #   uses: azure/container-actions/docker-login@master
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     email: ${{ secrets.DOCKER_EMAIL }}

    # - name: Build and push
    #   run: |
    #     docker build -t fauzif06/git:${{steps.get_tag.outputs.new_tag}} -f Dockerfile .
    #     docker push fauzif06/git:${{steps.get_tag.outputs.new_tag}}