name: Prod Deployment Workflow

on:
  release:
    types: [published]

jobs:
  job_1:
    name: Build, Push, Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master

      - name: Get the version of release
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}


      # - name: Docker Build Dev with Tag
      #   uses: azure/container-actions/docker-login@master
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     email: ${{ secrets.DOCKER_EMAIL }}

      # - name: Build and push
      #   run: |
      #     docker build -t fauzif06/git:${{steps.get_version.outputs.VERSION}} -f Dockerfile .
      #     docker push fauzif06/git:${{steps.get_version.outputs.VERSION}}
      